(function(){'use strict';window.Dashboard=window.Dashboard||{};
const hitAreas={};
const COLORS=['#5b5df0','#8b5cf6','#06b6d4','#13b981','#f59e0b','#ef4444','#ec4899','#3b82f6','#14b8a6','#84cc16'];
function css(name,fallback){return getComputedStyle(document.documentElement).getPropertyValue(name).trim()||fallback}
function setup(id){const canvas=document.getElementById(id);if(!canvas)return null;const rect=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.max(320,Math.floor(rect.width*dpr));canvas.height=Math.max(200,Math.floor(rect.height*dpr));const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);hitAreas[id]=[];return{canvas,ctx,w:rect.width,h:rect.height}}
function roundRect(ctx,x,y,w,h,r){const rr=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+rr,y);ctx.arcTo(x+w,y,x+w,y+h,rr);ctx.arcTo(x+w,y+h,x,y+h,rr);ctx.arcTo(x,y+h,x,y,rr);ctx.arcTo(x,y,x+w,y,rr);ctx.closePath()}
function grid(ctx,w,h,pad,max){ctx.strokeStyle=css('--line','#e5e7eb');ctx.lineWidth=1;ctx.fillStyle=css('--muted','#697386');ctx.font='10px Segoe UI';ctx.textAlign='right';for(let i=0;i<=4;i++){const y=pad.t+(h-pad.t-pad.b)*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();const value=Math.round(max*(1-i/4));ctx.fillText(Dashboard.num(value),pad.l-7,y+3)}}
function empty(ctx,w,h){ctx.fillStyle=css('--muted','#697386');ctx.font='12px Segoe UI';ctx.textAlign='center';ctx.fillText(Dashboard.t('noData'),w/2,h/2)}
function lineChart(id,labels,values){const o=setup(id);if(!o)return;const{ctx,w,h}=o;if(!values.length)return empty(ctx,w,h);const pad={t:25,r:20,b:42,l:42},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,max=Math.max(...values,1);grid(ctx,w,h,pad,max);
 const points=values.map((v,i)=>({x:pad.l+(values.length===1?cw/2:i*cw/(values.length-1)),y:pad.t+ch*(1-v/max),v,label:labels[i]}));
 const grad=ctx.createLinearGradient(0,pad.t,0,h-pad.b);grad.addColorStop(0,'rgba(91,93,240,.28)');grad.addColorStop(1,'rgba(91,93,240,0)');ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.lineTo(points[points.length-1].x,h-pad.b);ctx.lineTo(points[0].x,h-pad.b);ctx.closePath();ctx.fillStyle=grad;ctx.fill();
 ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle=COLORS[0];ctx.lineWidth=3;ctx.lineJoin='round';ctx.stroke();
 points.forEach(p=>{ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fillStyle=css('--surface','#fff');ctx.fill();ctx.lineWidth=3;ctx.strokeStyle=COLORS[0];ctx.stroke();hitAreas[id].push({x:p.x-11,y:p.y-11,w:22,h:22,label:p.label,value:p.v})});
 ctx.fillStyle=css('--muted','#697386');ctx.font='10px Segoe UI';ctx.textAlign='center';labels.forEach((l,i)=>ctx.fillText(String(l).slice(0,12),points[i].x,h-14));bindTooltip(o.canvas,id)}
function hBar(id,labels,values){const o=setup(id);if(!o)return;const{ctx,w,h}=o;if(!values.length)return empty(ctx,w,h);const pad={t:12,r:38,b:12,l:112},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,max=Math.max(...values,1),slot=ch/values.length,bh=Math.min(17,slot*.56);ctx.font='10px Segoe UI';values.forEach((v,i)=>{const y=pad.t+i*slot+(slot-bh)/2;ctx.fillStyle=css('--surface-2','#f8faff');roundRect(ctx,pad.l,y,cw,bh,bh/2);ctx.fill();const width=Math.max(3,cw*v/max),g=ctx.createLinearGradient(pad.l,0,pad.l+width,0);g.addColorStop(0,COLORS[i%COLORS.length]);g.addColorStop(1,COLORS[(i+1)%COLORS.length]);ctx.fillStyle=g;roundRect(ctx,pad.l,y,width,bh,bh/2);ctx.fill();ctx.fillStyle=css('--muted','#697386');ctx.textAlign='right';ctx.fillText(String(labels[i]).slice(0,18),pad.l-9,y+bh*.72);ctx.textAlign='left';ctx.font='700 9px Segoe UI';ctx.fillStyle=css('--text','#131a2b');ctx.fillText(Dashboard.num(v),pad.l+width+6,y+bh*.72);ctx.font='10px Segoe UI';hitAreas[id].push({x:pad.l,y,w:Math.max(width,24),h:bh,label:labels[i],value:v})});bindTooltip(o.canvas,id)}
function vBar(id,labels,values){const o=setup(id);if(!o)return;const{ctx,w,h}=o;if(!values.length)return empty(ctx,w,h);const pad={t:22,r:20,b:42,l:42},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,max=Math.max(...values,1);grid(ctx,w,h,pad,max);const slot=cw/values.length,bw=Math.min(52,slot*.52);values.forEach((v,i)=>{const x=pad.l+i*slot+(slot-bw)/2,y=pad.t+ch*(1-v/max),height=ch*v/max;const g=ctx.createLinearGradient(0,y,0,y+height);g.addColorStop(0,COLORS[i%COLORS.length]);g.addColorStop(1,COLORS[(i+1)%COLORS.length]);ctx.fillStyle=g;roundRect(ctx,x,y,bw,height,8);ctx.fill();ctx.fillStyle=css('--muted','#697386');ctx.font='10px Segoe UI';ctx.textAlign='center';ctx.fillText(String(labels[i]).slice(0,10),x+bw/2,h-14);ctx.fillStyle=css('--text','#131a2b');ctx.font='700 10px Segoe UI';ctx.fillText(Dashboard.num(v),x+bw/2,Math.max(12,y-7));hitAreas[id].push({x,y,w:bw,h:height,label:labels[i],value:v})});bindTooltip(o.canvas,id)}
function doughnut(id,labels,values){const o=setup(id);if(!o)return;const{ctx,w,h}=o,total=values.reduce((a,b)=>a+b,0);if(!total)return empty(ctx,w,h);const cx=w*.39,cy=h*.48,r=Math.min(w*.31,h*.31),inner=r*.66;let angle=-Math.PI/2;values.forEach((v,i)=>{const end=angle+Math.PI*2*v/total;ctx.beginPath();ctx.arc(cx,cy,r,angle,end);ctx.arc(cx,cy,inner,end,angle,true);ctx.closePath();ctx.fillStyle=COLORS[i%COLORS.length];ctx.fill();hitAreas[id].push({type:'arc',cx,cy,r,inner,a1:angle,a2:end,label:labels[i],value:v});angle=end});ctx.fillStyle=css('--text','#131a2b');ctx.textAlign='center';ctx.font='800 26px Segoe UI';ctx.fillText(Dashboard.num(total),cx,cy+2);ctx.font='9px Segoe UI';ctx.fillStyle=css('--muted','#697386');ctx.fillText(Dashboard.t('totalEvents'),cx,cy+20);const lx=w*.69,top=58;labels.forEach((l,i)=>{const y=top+i*38;ctx.fillStyle=COLORS[i%COLORS.length];ctx.beginPath();ctx.arc(lx,y,5,0,Math.PI*2);ctx.fill();ctx.fillStyle=css('--text','#131a2b');ctx.textAlign='left';ctx.font='700 10px Segoe UI';ctx.fillText(String(l),lx+12,y-2);ctx.fillStyle=css('--muted','#697386');ctx.font='9px Segoe UI';ctx.fillText(`${Dashboard.num(values[i])} · ${Math.round(values[i]/total*100)}%`,lx+12,y+12)});bindTooltip(o.canvas,id)}
function bindTooltip(canvas,id){if(canvas.dataset.tipBound)return;canvas.dataset.tipBound='1';const tip=document.getElementById('tip-'+id);canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let hit=null;for(const a of hitAreas[id]||[]){if(a.type==='arc'){const dx=x-a.cx,dy=y-a.cy,d=Math.hypot(dx,dy);let ang=Math.atan2(dy,dx);if(ang< -Math.PI/2)ang+=Math.PI*2;if(d>=a.inner&&d<=a.r&&ang>=a.a1&&ang<=a.a2)hit=a}else if(x>=a.x&&x<=a.x+a.w&&y>=a.y&&y<=a.y+a.h)hit=a;if(hit)break}if(!hit){tip.style.opacity=0;return}tip.innerHTML=`<b>${String(hit.label)}</b><br>${Dashboard.num(hit.value)} ${Dashboard.t('events')}`;tip.style.left=x+'px';tip.style.top=y+'px';tip.style.opacity=1});canvas.addEventListener('mouseleave',()=>tip.style.opacity=0)}
Dashboard.Charts={render(){const e=Dashboard.state.filtered,m=Dashboard.state.mapping;const month=Dashboard.countBy(e,x=>Dashboard.monthOf(x),1,12);lineChart('chartMonth',month.labels.map(Dashboard.monthLabel),month.values);const status=Dashboard.countBy(e,x=>Dashboard.getStatus(x));doughnut('chartStatus',status.labels.map(Dashboard.statusLabel),status.values);[['chartCountry',m.country],['chartCity',m.city],['chartType',m.type],['chartOrganizer',m.organizer]].forEach(([id,key])=>{const d=Dashboard.topCount(e,x=>Dashboard.value(x,key),10);hBar(id,d.labels,d.values)});const years=Dashboard.countBy(e,x=>Dashboard.yearOf(x));vBar('chartYears',years.labels,years.values)}};
window.addEventListener('resize',()=>{clearTimeout(Dashboard._chartTimer);Dashboard._chartTimer=setTimeout(()=>Dashboard.Charts.render(),180)});
})();
