(function(){'use strict';window.Dashboard=window.Dashboard||{};
const ids={search:'filterSearch',year:'filterYear',month:'filterMonth',country:'filterCountry',city:'filterCity',type:'filterType',organizer:'filterOrganizer',status:'filterStatus'};
Dashboard.Filters={
 init(){this.nodes=Object.fromEntries(Object.entries(ids).map(([k,id])=>[k,document.getElementById(id)]));Object.values(this.nodes).forEach(n=>n.addEventListener(n.tagName==='INPUT'?'input':'change',()=>this.apply()));document.getElementById('resetFilters').addEventListener('click',()=>this.reset())},
 populate(){const s=Dashboard.state,m=s.mapping;this.fill('year',Dashboard.unique(s.events.map(e=>Dashboard.yearOf(e))),true);this.fill('month',Array.from({length:12},(_,i)=>i+1),true,v=>Dashboard.monthLabel(v));this.fill('country',Dashboard.unique(s.events.map(e=>Dashboard.value(e,m.country))),true);this.fill('city',Dashboard.unique(s.events.map(e=>Dashboard.value(e,m.city))),true);this.fill('type',Dashboard.unique(s.events.map(e=>Dashboard.value(e,m.type))),true);this.fill('organizer',Dashboard.unique(s.events.map(e=>Dashboard.value(e,m.organizer))),true);this.fill('status',['upcoming','ongoing','ended'],true,v=>Dashboard.statusLabel(v))},
 fill(key,values,all,label=x=>x){const n=this.nodes[key],old=n.value;n.innerHTML='';if(all){const o=document.createElement('option');o.value='';o.textContent=Dashboard.t('all');n.appendChild(o)}values.filter(v=>v!==''&&v!==null&&v!==undefined).sort((a,b)=>String(a).localeCompare(String(b),Dashboard.state.lang)).forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=label(v);n.appendChild(o)});if([...n.options].some(o=>o.value===old))n.value=old},
 updateActiveCount(){const active=Object.values(this.nodes||{}).filter(n=>n&&n.value).length;const badge=document.getElementById('activeFilterCount');if(badge)badge.textContent=`${Dashboard.num(active)} ${Dashboard.t('active')}`},
 apply(){const f={search:this.nodes.search.value.trim().toLowerCase(),year:this.nodes.year.value,month:this.nodes.month.value,country:this.nodes.country.value,city:this.nodes.city.value,type:this.nodes.type.value,organizer:this.nodes.organizer.value,status:this.nodes.status.value};const m=Dashboard.state.mapping;Dashboard.state.filtered=Dashboard.state.events.filter(e=>{const name=String(Dashboard.value(e,m.name)||'').toLowerCase();return(!f.search||name.includes(f.search)||Object.values(e).some(v=>String(v??'').toLowerCase().includes(f.search)))&&(!f.year||String(Dashboard.yearOf(e))===f.year)&&(!f.month||String(Dashboard.monthOf(e))===f.month)&&(!f.country||String(Dashboard.value(e,m.country))===f.country)&&(!f.city||String(Dashboard.value(e,m.city))===f.city)&&(!f.type||String(Dashboard.value(e,m.type))===f.type)&&(!f.organizer||String(Dashboard.value(e,m.organizer))===f.organizer)&&(!f.status||Dashboard.getStatus(e)===f.status)});Dashboard.state.page=1;this.updateActiveCount();Dashboard.renderAll()},
 reset(){Object.values(this.nodes).forEach(n=>n.value='');this.apply()}
};})();
