(function(){'use strict';window.Dashboard=window.Dashboard||{};
Dashboard.Table={
 init(){this.table=document.getElementById('eventsTable');this.thead=this.table.querySelector('thead');this.tbody=this.table.querySelector('tbody');document.getElementById('pagePrev').onclick=()=>{if(Dashboard.state.page>1){Dashboard.state.page--;this.render()}};document.getElementById('pageNext').onclick=()=>{if(Dashboard.state.page<this.totalPages()){Dashboard.state.page++;this.render()}};document.getElementById('pageSize').onchange=e=>{Dashboard.state.pageSize=+e.target.value;Dashboard.state.page=1;this.render()};document.getElementById('columnsBtn').onclick=()=>document.getElementById('columnPicker').classList.toggle('hidden');document.addEventListener('click',e=>{const p=document.getElementById('columnPicker');if(!p.contains(e.target)&&e.target.id!=='columnsBtn')p.classList.add('hidden')});document.getElementById('exportCsv').onclick=()=>this.exportCsv();document.getElementById('exportXlsx').onclick=()=>this.exportXlsx();document.getElementById('printTable').onclick=()=>window.print()},
 defaultColumns(){const m=Dashboard.state.mapping;return[m.id,m.name,m.category,m.type,m.country,m.city,m.organizer,m.startDate,m.endDate].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i)},
 buildColumns(){const stored=JSON.parse(localStorage.getItem('eventVisibleColumns')||'null');Dashboard.state.visibleColumns=stored&&stored.some(x=>Dashboard.state.headers.includes(x))?stored.filter(x=>Dashboard.state.headers.includes(x)):this.defaultColumns();const picker=document.getElementById('columnPicker');picker.innerHTML='';Dashboard.state.headers.forEach(h=>{const label=document.createElement('label');const cb=document.createElement('input');cb.type='checkbox';cb.checked=Dashboard.state.visibleColumns.includes(h);cb.onchange=()=>{if(cb.checked)Dashboard.state.visibleColumns.push(h);else Dashboard.state.visibleColumns=Dashboard.state.visibleColumns.filter(x=>x!==h);localStorage.setItem('eventVisibleColumns',JSON.stringify(Dashboard.state.visibleColumns));this.render()};label.append(cb,document.createTextNode(h));picker.appendChild(label)})},
 sorted(){const a=[...Dashboard.state.filtered],{sortKey,sortDir}=Dashboard.state;if(!sortKey)return a;return a.sort((x,y)=>{let av=x[sortKey],bv=y[sortKey];const ad=Dashboard.parseDate(av),bd=Dashboard.parseDate(bv);if(ad&&bd){av=ad;bv=bd}if(av===bv)return 0;if(av===null||av===undefined)return 1;if(bv===null||bv===undefined)return-1;return(av>bv?1:-1)*(sortDir==='asc'?1:-1)})},
 totalPages(){return Math.max(1,Math.ceil(Dashboard.state.filtered.length/Dashboard.state.pageSize))},
 render(){const cols=Dashboard.state.visibleColumns||[];this.thead.innerHTML='';const tr=document.createElement('tr');cols.forEach(h=>{const th=document.createElement('th');th.textContent=h+(Dashboard.state.sortKey===h?(Dashboard.state.sortDir==='asc'?' ▲':' ▼'):'');th.onclick=()=>{if(Dashboard.state.sortKey===h)Dashboard.state.sortDir=Dashboard.state.sortDir==='asc'?'desc':'asc';else{Dashboard.state.sortKey=h;Dashboard.state.sortDir='asc'}this.render()};tr.appendChild(th)});this.thead.appendChild(tr);this.tbody.innerHTML='';const all=this.sorted(),start=(Dashboard.state.page-1)*Dashboard.state.pageSize,rows=all.slice(start,start+Dashboard.state.pageSize);if(!rows.length){const r=document.createElement('tr'),c=document.createElement('td');c.colSpan=Math.max(cols.length,1);c.className='no-data-cell';c.textContent=Dashboard.t('noData');r.appendChild(c);this.tbody.appendChild(r)}rows.forEach(e=>{const r=document.createElement('tr');r.onclick=()=>Dashboard.Modal.open(e);cols.forEach(h=>{const c=document.createElement('td');c.dataset.label=h;const v=e[h];if(h===Dashboard.state.mapping.name)c.className='event-name';if(h===Dashboard.state.mapping.status){const s=Dashboard.getStatus(e);const p=document.createElement('span');p.className='status-pill status-'+s;p.textContent=Dashboard.statusLabel(s);c.appendChild(p)}else c.textContent=Dashboard.formatValue(v,h);r.appendChild(c)});this.tbody.appendChild(r)});this.table.setAttribute('aria-label',Dashboard.t('eventsTable'));document.getElementById('pageInfo').textContent=`${Dashboard.state.page} / ${this.totalPages()}`;document.getElementById('tableResultCount').textContent=`${Dashboard.num(Dashboard.state.filtered.length)} ${Dashboard.t('events')}`;document.getElementById('pagePrev').disabled=Dashboard.state.page<=1;document.getElementById('pageNext').disabled=Dashboard.state.page>=this.totalPages()},
 exportCsv(){const cols=Dashboard.state.visibleColumns,rows=[cols,...this.sorted().map(e=>cols.map(h=>e[h]??''))];const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');Dashboard.download(new Blob([csv],{type:'text/csv;charset=utf-8'}),'events-filtered.csv')},
 exportXlsx(){const cols=Dashboard.state.visibleColumns,records=this.sorted().map(e=>Object.fromEntries(cols.map(h=>[h,e[h]??'']))),wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(records);XLSX.utils.book_append_sheet(wb,ws,'Events');XLSX.writeFile(wb,'events-filtered.xlsx')}
};})();
